### PR TITLE
DEV: forward slashes forbidden

### PR DESCRIPTION
**Pull request by licode**
per https://github.com/NSLS-II/event-model/issues/11   @danielballan

### CODE REVIEW

**Comment by danielballan** [comment]
Tested:

```python
In [3]: doc = {'uid': 'asdf', 'time': 0, 'foo/bar': 'stuff'}

In [4]: jsonschema.validate(doc, event_model.schemas[event_model.DocumentNames.start])
   ...:
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
<snip>

In [5]: doc = {'uid': 'asdf', 'time': 0, 'foo.bar': 'stuff'}

In [6]: jsonschema.validate(doc, event_model.schemas[event_model.DocumentNames.start])
   ...:
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
<snip>

In [7]: doc = {'uid': 'asdf', 'time': 0, 'foobar': 'stuff'}

In [8]: jsonschema.validate(doc, event_model.schemas[event_model.DocumentNames.start])
   ...:
```

**Comment by danielballan** [comment]
Thanks, @licode.

**Comment by licode** [comment]
sure thing. I also did some local test.

**Comment by danielballan** [comment]
Cool, I figured. I just pasted some in here for the record.

**Pull request merged**
