### PR TITLE
ENH: Add document-composing tools.

### PR DESCRIPTION
**Pull request by danielballan**
The only public function is ``create_run``. It returns closures over other
functions, passing internal shared state to manage foreign keys, counters,
and some inter-document validation.

Submitted for early review. Do not merge.

Example usage:

```
import event_model                                                                                                                                                                            
start_doc, create_descriptor, create_resource, create_stop = event_model.create_run()                                                                                                         
print(start_doc)                                                                                                                                                                              
descriptor_doc, create_event = create_descriptor(data_keys={'motor': {'shape': [], 'dtype': 'number'}, 'image': {'shape': [512, 512], 'dtype': 'number', 'external': 'FILESTORE:'}}, name='pri
mary')                                                                                                                                                                                        
print(descriptor_doc)                                                                                                                                                                         
resource_doc, create_datum = create_resource(spec='TIFF', root='/tmp', resource_path='stack.tiff', resource_kwargs={})                                                                        
print(resource_doc)                                                                                                                                                                           
datum_doc = create_datum(datum_kwargs={'slice': 5})                                                                                                                                           
print(datum_doc)                                                                                                                                                                              
event_doc = create_event(data={'motor': 0, 'image': datum_doc['datum_id']}, timestamps={'motor': 0, 'image': 0}, filled={'image': False}, seq_num=1)                                          
print(event_doc)                                                                                                                                                                              
stop_doc = create_stop()                                                                                                                                                                      
print(stop_doc)    
```

### CODE REVIEW

**Comment by danielballan** [comment]
Note: I'm passing the whole document down into the closure for now, here and elsewhere. Eventually I think it would be better to pass down only the parts we need, for both safely (avoid shared mutable state where possible) and ability to reuse pieces of this API independently. For example, ophyd will want to run `create_resource` and `create_datum` without having run `create_run` or having access to a `start` document.

**Comment by ronpandolfi** [comment]
This is great. Could we also have a context-managed equivalent of `create_run` that generates `stop_doc` and runs a callback?

**Comment by tacaswell** [comment]
Something like

``python
with create_run as bundle_of_stuff:
    ...
```

Having that for all of the generations makes sense to me too...

Having `create_run` return a named tuple or SimpleNamespace would make sense to me.

I am partial to defined in-line functions, but partial makes more sense incase we want those low-level functions else where?

**Comment by danielballan** [comment]
> Could we also have a context-managed equivalent of create_run that generates stop_doc and runs a callback?

> Having that for all of the generations makes sense to me too...

Sure, I'll try building context managers on top of the functions and see how it looks.

> Having create_run return a named tuple or SimpleNamespace would make sense to me.

Yeah, I thought about a `namedtuple`. Will do.

> I am partial to defined in-line functions, but partial makes more sense incase we want those low-level functions else where?

Right. I started with in-line functions and quickly changed course for that reason. For example, ophyd will need to be able to use `create_resource` without knowing the RunStart yet, maybe putting in `{'run_start': None}` as a placeholder. It might also be useful to be able to access these things individually in tests, I guess, but it's not that big a deal to just generate them. Meh.

**Comment by CJ-Wright** [comment]
:+1:

**Comment by tacaswell** [comment]
> For example, ophyd will need to be able to use `create_resource` without

maybe the Resource factory should just be stand alone them?  How terrible would it look to pass a resource factory into `trigger` (I think pretty terrible, but could be convinced otherwise).

**Comment by danielballan** [comment]
What's the rationale for defining functions locally? It makes them impossible to individually document and test. It seems a bit too clever to my taste.

If the goal is to make sure they are definitely not part of the public API, I think leaving them out of `__all__` is good enough for now. Is there another reason?

**Comment by danielballan** [comment]
I would like to propose merging this in its current form and experimenting with context managers separately, aiming to eventually move experiments up stream when we find a good pattern.

**Comment by awalter-bnl** [comment]
merging as it has been approved and I would like to use it for suitcase_csv tests

**Pull request merged**
